version: "3"
services:
  
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}      
      - TZ=${TZLON}
    volumes:
      - ${APPDATA}sonarr:/config
      - ${GMEDIA}
      - ${DOWNLOAD}
    ports:
      - 8989:8989
      
  radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZLON}
    volumes:
      - ${APPDATA}radarr:/config
      - ${GMEDIA}
      - ${DOWNLOAD}
    ports:
      - 7878:7878
      
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZLON}
    volumes:
      - ${APPDATA}sabnzdb:/config
      - ${DOWNLOAD}
      - ${DOWNLOAD_LOC}    
    ports:
      - 8080:8080
      
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=${USVC}
      - PGID=${GSVC}
      - TZ=${TZLON}
    volumes:
      - ${APPDATA}ombi:/config
    ports:
      - 3579:3579
