version: "3"
services:
  
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}      
      - TZ=${TZ}
    volumes:
      - ${APPDATA}sonarr:/config
      - ${GMEDIA}
      - ${DOWNLOAD}
    ports:
      - 8989:8989
      
  radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}radarr:/config
      - ${GMEDIA}
      - ${DOWNLOAD}
    ports:
      - 7878:7878
      
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}sabnzdb:/config
      - ${DOWNLOAD}
    ports:
      - 8080:8080
      
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=${USVC}
      - PGID=${GSVC}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}ombi:/config
    ports:
      - 3579:3579
      
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=${USVC}
      - PGID=${GSVC}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - ${APPDATA}jackett:/config
    ports:
      - 9117:9117
      
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}tautulli:/config
    ports:
      - 8181:8181
      
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${USVC}
      - PGID=${GSVC}
      - PLEX_CLAIM=${PLEXTOKEN}
    volumes:
      - ${APPDATA}plex:/config
      - ${GMEDIA-TV}:/tv
      - ${GMEDIA-MOVIE}:/movies

